import 'package:get/get.dart';

class Translator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'مقالات': 'doc',
          'بازدید کنندگان': 'Viewers',
          'Beta version.If you exprience any problem or having a suggestion please tell us.':'Beta version.If you exprience any problem or having a suggestion please tell us.',
          'English': "فارسی",
          'ModSec Admin Panel': 'ModSec Admin Panel',
          'Dashboard': 'Dashboard',
          'CPU Usage': 'CPU Usage',
          'Cloud Usage': 'Cloud Usage',
          'Memory Usage': 'Memory Usage',
          'Traffic Usage': 'Traffic Usage',
          'Attacks per Application': 'Attacks per Application',
          'Welcome Admin!': 'Welcome Admin!',
          'Time remaining:': 'Time remaining:',
          'admin1': 'admin1',
          'Error': 'Error',
          'Quick Summary': 'Quick Summary',
          'Please fill the inputs correctly!': 'Please fill the inputs correctly!',
          'Login Successful!': 'Login Successful!',
          'Welcome dear test.': 'Welcome dear test.',
          'Invalid username or password': 'Invalid username or password',
          'Check your internet connection !': 'Check your internet connection!',
          'Logout': 'Logout',
          'Are you sure you want to logout?': 'Are you sure you want to logout?',
          'Cancel': 'Cancel',
          'Confirm': 'Confirm',
          'Profile': 'Profile',
          'Settings': 'Settings',
          'Idle Alert': 'Idle Alert',
          'You have been idle for some min. Do you want to stay?': 'You have been idle for some min. Do you want to stay?',
          'YES': 'YES',
          'Websites': 'Websites',
          'Statistics': 'Statistics',
          'System Log': 'System Log',
          'Dark Mode': 'Dark Mode',
          'Language': 'Language',
          'Login': 'Login',
          'Welcome to WAF2Flutter!': 'Welcome to WAF2Flutter!',
          'Username': 'Username',
          'Password': 'Password',
          'Demo Login method using pre defined username and pass': 'Demo Login method using pre defined username and pass',
          'Status': 'Status',
          'Visitors: ': 'Visitors: ',
          'Last refresh: ': 'Last refresh: ',
          'Suspected: ': 'Suspected: ',
          'Critical: ': 'Critical: ',
          'Safe': 'Safe',
          'System': 'System',
          'Interfaces': 'Interfaces',
          'WAF is ON!': 'WAF is ON!',
          'Time remaining:   ':'Time remaining:   ',
          'Waf Actions': 'Waf Actions',
          'Loading': 'Loading',
          'Checking status...': 'Checking status...',
          'Unable to get status': 'Unable to get status',
          'Unsafe': 'Unsafe',
          'Check Confg': 'Check Confg',
          'Start Engine': 'Start Engine',
          'Stop Engine': 'Stop Engine',
          'WAF started successfully!': 'WAF started successfully!',
          'Failed to start WAF': 'Failed to start WAF',
          'WAF stopped successfully!': 'WAF stopped successfully!',
          'Failed to stop WAF': 'Failed to stop WAF',
          'Update Status': 'Update Status',
          'Refresh Status': 'Refresh Status',
          'please refresh to check..': 'please refresh to check..',
          'Current: ': 'Current: ',
          'WAF Radar Overview': 'WAF Radar Overview',
          'Critical Errors': 'Critical Errors',
          'Warnings': 'Warnings',
          'Messages': 'Messages',
          'No triggered rules found.': 'No triggered rules found.',
          'The #': 'The #',
          'most triggered rule: ': 'most triggered rule: ',
          'Configuration Files': 'Configuration Files',
          'ModSecurity': 'ModSecurity',
          'CRS Setup': 'CRS Setup',
          'Nginx': 'Nginx',
          'Config File: ': 'Config File: ',
          'Content of ': 'Content of ',
          'Enter your configuration here...': 'Enter your configuration here...',
          'Restore': 'Restore',
          'Save': 'Save',
          'Content cannot be empty': 'Content cannot be empty',
          'updated successfully': 'updated successfully',
          'Failed to update ': 'Failed to update ',
          'restored successfully': 'restored successfully',
          'Failed to restore ': 'Failed to restore ',
          'Enter title of the rule:': 'Enter title of the rule:',
          'Type rule name...': 'Type rule name...',
          'Content of the rule': 'Content of the rule',
          'Rule added successfully': 'Rule added successfully',
          'Please fill in both fields': 'Please fill in both fields',
          'Change Waf Mode': 'Change Waf Mode',
          'Critical ! The dangerous requests cannot be blocked waf is off!': 'Critical ! The dangerous requests cannot be blocked waf is off!',
          'Warning waf is only detect the Critical requests.': 'Warning waf is only detect the Critical requests.',
          'Waf is blooking Critical Requests!': 'Waf is blooking Critical Requests!',
          'Change': 'Change',
          'SecRuleEngine set to ': 'SecRuleEngine set to ',
          'successfully': 'successfully',
          'Failed to set SecRuleEngine': 'Failed to set SecRuleEngine',
          'Your IP Server: ': 'Your IP Server: ',
          'Search among rules:': 'Search among rules:',
          'Create New Rule': 'Create New Rule',
          'Download': 'Download',
          'Rules restored successfully': 'Rules restored successfully',
          'Failed to restore rules': 'Failed to restore rules',
          'Manage ModSecurity rules and configuration': 'Manage ModSecurity rules and configuration',
          'Rule Name': 'Rule Name',
          'Edit Rule': 'Edit Rule',
          'Remove': 'Remove',
          'This shows the status of the rule (enabled/disabled)': 'This shows the status of the rule (enabled/disabled)',
          'You can delete this rule via this key': 'You can delete this rule via this key',
          'Rule status updated.': 'Rule status updated.',
          'Failed to update rule status.': 'Failed to update rule status.',
          'Rule deleted successfully': 'Rule deleted successfully',
          'Failed to delete rule': 'Failed to delete rule',
          'Enter rule content...': 'Enter rule content...',
          'Internal Error Logs': 'Internal Error Logs',
          'Showing last ': 'Showing last ',
          'logs': 'logs',
          'Download Full Log': 'Download Full Log',
          'Show': 'Show',
          'Filter': 'Filter',
          'Select Filter': 'Select Filter',
          'Apply': 'Apply',
          'Log Details': 'Log Details',
          'Timestamp: ': 'Timestamp: ',
          'Message: ': 'Message: ',
          'Close': 'Close',
          'Nginx Logs': 'Nginx Logs',
          'Warnings:': 'Warnings:',
          'IP: ': 'IP: ',
          'Request: ': 'Request: ',
          'Status: ': 'Status: ',
          'Bytes: ': 'Bytes: ',
          'Referrer: ': 'Referrer: ',
          'User-Agent: ': 'User-Agent: ',
          'Filter Options': 'Filter Options',
          'User Action Logs': 'User Action Logs',
          'Level: ': 'Level: ',
          'Waf Logs': 'Waf Logs',
          'Clear All Logs': 'Clear All Logs',
          'Method: ': 'Method: ',
          'Path: ': 'Path: ',
          'Alerts:': 'Alerts:',
          'No alerts': 'No alerts',
          'Rule ID: ': 'Rule ID: ',
          'Severity: ': 'Severity: ',
          'File: ': 'File: ',
          'Line: ': 'Line: ',
          'No logs available. Check data source or filters.': 'No logs available. Check data source or filters.',
          'This will clear all logs. Proceed?': 'This will clear all logs. Proceed?',
          'No': 'No',
          'Yes': 'Yes',
          '#': '#',
          'IP Address': 'IP Address',
          'Logs': 'Logs',
          'Results': 'Results',
          'Summary': 'Summary',
          'Websites Running': 'Websites Running',
          'Disable Websites': 'Disabled Websites',
          'Name': 'Name',
          'Application': 'Application',
          'Listens to': 'Listens to',
          'Real web server': 'Real Web Server',
          'Status Notes': 'Status Notes',
          'Mode': 'Mode',
          'Actions': 'Actions',
          'Website Started': 'Website Started',
          'Confirm Deletion': 'Confirm Deletion',
          'This action cannot be undone': 'This action cannot be undone',
          'WAF Protection': 'WAF Protection',
          'Configuration': 'Configuration',
          'Audit Logs for ': 'Audit Logs for ',
          'Audit Logs': 'Audit Logs',
          'Attack Summary': 'Attack Summary',
          'Warning: ': 'Warning: ',
          'Notice: ': 'Notice: ',
          'Error: ': 'Error: ',
          'Total Requests: ': 'Total Requests: ',
          'Reload': 'Reload',
          'audit logs': 'audit logs',
          'No audit logs available.': 'No audit logs available.',
          'Audit Log Details': 'Audit Log Details',
          'ID: ': 'ID: ',
          'entries': 'entries',
          'Search': 'Search',
          'Local rule exclusion': 'Local Rule Exclusion',
          'Exclusion Path:': 'Exclusion Path:',
          'Rule ID:': 'Rule ID:',
          'Attack Name:': 'Attack Name:',
          'Global Exclusion': 'Global Exclusion',
          'Debug Logs': 'Debug Logs',
          'Debug Log Details': 'Debug Log Details',
          'Refresh': 'Refresh',
          'Nginx Configuration': 'Nginx Configuration',
          'ModSecurity Configuration': 'ModSecurity Configuration',
          'Success': 'Success',
          'Rule updated successfully': 'Rule updated successfully',
          'Rules downloaded successfully': 'Rules downloaded successfully',
          'Failed to update rule - check logs or backend': 'Failed to update rule - check logs or backend',
          'Failed to delete rule - check logs or backend': 'Failed to delete rule - check logs or backend',
          'Failed to download rules': 'Failed to download rules',
          'Enabled': 'Enabled',
          'Disabled': 'Disabled',
          'Deploy': 'Deploy',
          'Delete': 'Delete',
          'Add New Application': 'Add New Application',
          'Application Name': 'Application Name',
          'Application Url': 'Application Url',
          'Applications Pending to Preview': 'Applications Pending to Preview',
          'No pending applications.': 'No pending applications.',
          'Please fill in both fields.': 'Please fill in both fields.',
          'Cannot upload. Current status: ': 'Cannot upload. Current status: ',
          'This website is already deployed.': 'This website is already deployed.',
          'Cannot deploy. Current status: ': 'Cannot deploy. Current status: ',
          'Canceled': 'Canceled',
          'You have canceled the action.': '.',
          'This page is currently at developments':'This page is currently at developments',
          'Disable Cinematic Mode': 'Disable Cinematic Mode',
          'Enable Cinematic Mode': 'Enable Cinematic Mode',
          'Upload this website to the server': 'Upload this website to the server',
          'Deploy this website to the server': 'Deploy this website to the server',
          'Delete this website from the pending list': 'Delete this website from the pending list',
          'Introduce': 'Introduce',
          'Setup': 'Setup',
          'Control Panel': 'Control Panel',
          'API Reference': 'API Reference',
          'Developer Final Thoughts': 'Developer Final Thoughts',
          'Dark Mode': 'Dark Mode',
          'فارسی': 'Persian',
          'Welcome to WAF Manager': 'Welcome to WAF Manager',
          'The WAF Manager is a powerful tool for managing Web Application Firewalls (WAFs), monitoring website security, and configuring server settings. This section introduces its key features and how to get started.': 'The WAF Manager is a powerful tool for managing Web Application Firewalls (WAFs), monitoring website security, and configuring server settings. This section introduces its key features and how to get started.',
          'Key Features': 'Key Features',
          '- Website Management: Add, edit, deploy, and monitor websites.\n- WAF Configuration: Manage ModSecurity rules and exclusions.\n- Log Statistics: View audit and debug logs with summaries.\n- Responsive Interface: Works on mobile, tablet, and desktop.\n- Customization: Toggle dark mode, cinematic mode, and languages (English/Persian).': '- Website Management: Add, edit, deploy, and monitor websites.\n- WAF Configuration: Manage ModSecurity rules and exclusions.\n- Log Statistics: View audit and debug logs with summaries.\n- Responsive Interface: Works on mobile, tablet, and desktop.\n- Customization: Toggle dark mode, cinematic mode, and languages (English/Persian).',
          'How to Use': 'How to Use',
          '1. Navigate using the sidebar (visible on desktop or via the menu icon on mobile).\n2. Start by adding a website in the Setup section.\n3. Use the Control Panel to manage WAF settings and view logs.\n4. Refer to the API Reference for advanced integrations.\n5. Check Developer Final Thoughts for tips and best practices.': '1. Navigate using the sidebar (visible on desktop or via the menu icon on mobile).\n2. Start by adding a website in the Setup section.\n3. Use the Control Panel to manage WAF settings and view logs.\n4. Refer to the API Reference for advanced integrations.\n5. Check Developer Final Thoughts for tips and best practices.',
          'Next Steps': 'Next Steps',
          'Go to the Setup section to add your first website or explore the Control Panel to manage existing ones.': 'Go to the Setup section to add your first website or explore the Control Panel to manage existing ones.',
          'Setup Guide': 'Setup Guide',
          'This section explains how to add and deploy websites in the WAF Manager application.': 'This section explains how to add and deploy websites in the WAF Manager application.',
          'Adding a New Website': 'Adding a New Website',
          '1. Navigate to the Add Website section via the sidebar.\n2. In the Add New Application panel:\n   - Enter an Application Name (e.g., \'MyWebsite\', no spaces).\n   - Enter the Application URL (e.g., \'www.mywebsite.com\').\n3. Click \'Save\' to add the website to the pending list.\n4. A confirmation message will appear if successful.': '1. Navigate to the Add Website section via the sidebar.\n2. In the Add New Application panel:\n   - Enter an Application Name (e.g., \'MyWebsite\', no spaces).\n   - Enter the Application URL (e.g., \'www.mywebsite.com\').\n3. Click \'Save\' to add the website to the pending list.\n4. A confirmation message will appear if successful.',
          'Managing Pending Websites': 'Managing Pending Websites',
          'Pending websites appear in the Applications Pending to Preview table. For each website, you can:\n- Upload: If the status is \'Waiting for zip\', click the upload icon to provide a zip file.\n- Deploy: If the status is \'Ready to deploy!\', click the cloud upload icon to deploy to the server.\n- Delete: Click the delete icon to remove the website from the list.\nNote: Ensure the status is correct before performing actions. Errors will display as snackbar messages.': 'Pending websites appear in the Applications Pending to Preview table. For each website, you can:\n- Upload: If the status is \'Waiting for zip\', click the upload icon to provide a zip file.\n- Deploy: If the status is \'Ready to deploy!\', click the cloud upload icon to deploy to the server.\n- Delete: Click the delete icon to remove the website from the list.\nNote: Ensure the status is correct before performing actions. Errors will display as snackbar messages.',
          'Tips': 'Tips',
          '- Verify the URL format before saving.\n- Upload valid zip files to avoid deployment errors.\n- Check the Control Panel to manage deployed websites.': '- Verify the URL format before saving.\n- Upload valid zip files to avoid deployment errors.\n- Check the Control Panel to manage deployed websites.',
          'The Control Panel is the central hub for managing websites, configuring WAF settings, and monitoring logs.': 'The Control Panel is the central hub for managing websites, configuring WAF settings, and monitoring logs.',
          'Website Management': 'Website Management',
          '1. Access the Websites Dashboard via the Control Panel.\n2. Use the tabs:\n   - Websites Running: View active websites.\n   - Disabled Websites: View inactive websites.\n3. For each website:\n   - View Logs: Click the magnifying glass to see audit/debug logs.\n   - Edit: Click the edit icon to configure settings.\n   - Start/Stop: Use play/pause icons to toggle status.\n   - Delete: Click the delete icon and confirm.\n   - Mode: Select \'enabled\' or \'disabled\' from the dropdown.': '1. Access the Websites Dashboard via the Control Panel.\n2. Use the tabs:\n   - Websites Running: View active websites.\n   - Disabled Websites: View inactive websites.\n3. For each website:\n   - View Logs: Click the magnifying glass to see audit/debug logs.\n   - Edit: Click the edit icon to configure settings.\n   - Start/Stop: Use play/pause icons to toggle status.\n   - Delete: Click the delete icon and confirm.\n   - Mode: Select \'enabled\' or \'disabled\' from the dropdown.',
          'WAF Configuration': 'WAF Configuration',
          '1. Select a website and go to the WAF Protection tab.\n2. Manage ModSecurity rules:\n   - Search: Filter rules by name.\n   - Create: Click \'Create New Rule\', enter title/content, and save.\n   - Edit: Click \'Edit Rule\' to modify content.\n   - Delete: Click the delete icon.\n   - Toggle: Enable/disable rules with the switch.\n3. Backup/Restore:\n   - Download: Save a backup of rules.\n   - Restore: Upload a backup file.\n4. Configure Exclusions:\n   - Local: Set exclusion paths, rule IDs, or attack names.\n   - Global: Set global rule exclusions.': '1. Select a website and go to the WAF Protection tab.\n2. Manage ModSecurity rules:\n   - Search: Filter rules by name.\n   - Create: Click \'Create New Rule\', enter title/content, and save.\n   - Edit: Click \'Edit Rule\' to modify content.\n   - Delete: Click the delete icon.\n   - Toggle: Enable/disable rules with the switch.\n3. Backup/Restore:\n   - Download: Save a backup of rules.\n   - Restore: Upload a backup file.\n4. Configure Exclusions:\n   - Local: Set exclusion paths, rule IDs, or attack names.\n   - Global: Set global rule exclusions.',
          'Log Statistics': 'Log Statistics',
          '1. Audit Logs:\n   - Summary: View attack summary charts and counts (Critical, Warning, Notice, Error, Total Requests).\n   - Audit Logs: Click a log to see details (ID, Timestamp, Level, Message).\n   - Reload: Refresh the log list.\n2. Debug Logs:\n   - Filter: Select entries (5-100), enter search terms, or choose a log level (e.g., Error).\n   - Refresh: Reload logs.\n   - Details: Click a log to view full information.': '1. Audit Logs:\n   - Summary: View attack summary charts and counts (Critical, Warning, Notice, Error, Total Requests).\n   - Audit Logs: Click a log to see details (ID, Timestamp, Level, Message).\n   - Reload: Refresh the log list.\n2. Debug Logs:\n   - Filter: Select entries (5-100), enter search terms, or choose a log level (e.g., Error).\n   - Refresh: Reload logs.\n   - Details: Click a log to view full information.',
          'Interface Customization': 'Interface Customization',
          '- Cinematic Mode: Toggle for a blurred background effect.\n- Dark Mode: Switch via the sidebar.\n- Language: Change to English or Persian.\n- Responsive: Adapts to mobile, tablet, and desktop.': '- Cinematic Mode: Toggle for a blurred background effect.\n- Dark Mode: Switch via the sidebar.\n- Language: Change to English or Persian.\n- Responsive: Adapts to mobile, tablet, and desktop.',
          'This section provides guidance on using the WAF Manager’s backend APIs for advanced integrations.': 'This section provides guidance on using the WAF Manager’s backend APIs for advanced integrations.',
          'Overview': 'Overview',
          'The WAF Manager interacts with a backend server to perform actions like fetching logs, updating configurations, and managing rules. APIs are used for:\n- Retrieving audit and debug logs.\n- Managing ModSecurity rules.\n- Deploying websites.\n- Updating Nginx and ModSecurity configurations.': 'The WAF Manager interacts with a backend server to perform actions like fetching logs, updating configurations, and managing rules. APIs are used for:\n- Retrieving audit and debug logs.\n- Managing ModSecurity rules.\n- Deploying websites.\n- Updating Nginx and ModSecurity configurations.',
          'How to Use APIs': 'How to Use APIs',
          '1. Obtain an API token from your administrator.\n2. Use a tool like Postman or cURL to send requests.\n3. Include the token in the Authorization header.\n4. Refer to the endpoint documentation (contact your administrator for details).\nNote: API endpoints are not publicly exposed in this guide. Request access for specific documentation.': '1. Obtain an API token from your administrator.\n2. Use a tool like Postman or cURL to send requests.\n3. Include the token in the Authorization header.\n4. Refer to the endpoint documentation (contact your administrator for details).\nNote: API endpoints are not publicly exposed in this guide. Request access for specific documentation.',
          'Example Actions': 'Example Actions',
          '- Fetch Logs: Retrieve logs for a website.\n- Update Rule: Modify a ModSecurity rule.\n- Deploy Website: Deploy a pending website to the server.\nContact support for endpoint URLs and parameters.': '- Fetch Logs: Retrieve logs for a website.\n- Update Rule: Modify a ModSecurity rule.\n- Deploy Website: Deploy a pending website to the server.\nContact support for endpoint URLs and parameters.',
          'This section shares insights and best practices from the WAF Manager developers to help you use the application effectively.': 'This section shares insights and best practices from the WAF Manager developers to help you use the application effectively.',
          'Best Practices': 'Best Practices',
          '- Regularly Monitor Logs: Check audit and debug logs weekly to catch potential issues.\n- Backup Rules: Always download a backup before modifying WAF rules.\n- Test Deployments: Use the pending website feature to preview before deploying.\n- Update Configurations Carefully: Validate Nginx and ModSecurity changes to avoid errors.\n- Use Filters: Narrow down logs with search and level filters for faster analysis.': '- Regularly Monitor Logs: Check audit and debug logs weekly to catch potential issues.\n- Backup Rules: Always download a backup before modifying WAF rules.\n- Test Deployments: Use the pending website feature to preview before deploying.\n- Update Configurations Carefully: Validate Nginx and ModSecurity changes to avoid errors.\n- Use Filters: Narrow down logs with search and level filters for faster analysis.',
          'Tips for Efficiency': 'Tips for Efficiency',
          '- Enable Cinematic Mode for a modern interface (optional).\n- Switch to Persian for localized text if preferred.\n- Use tooltips (hover over icons) for quick action descriptions.\n- Contact support for API access to automate tasks.\n- Keep the application updated for new features and security fixes.': '- Enable Cinematic Mode for a modern interface (optional).\n- Switch to Persian for localized text if preferred.\n- Use tooltips (hover over icons) for quick action descriptions.\n- Contact support for API access to automate tasks.\n- Keep the application updated for new features and security fixes.',
          'Support': 'Support',
          'For issues, contact your system administrator or support team. Provide log details and error messages for faster resolution.': 'For issues, contact your system administrator or support team. Provide log details and error messages for faster resolution.',
        },
        'fa': {
          'doc': 'مقالات',
          'This page is currently at developments':'این صفحه در نسخه بتا در حال بروزرسانی می باشد.',
          'Internal Error Logs': 'لاگ‌های خطای داخلی',
          'Showing last ': 'نمایش آخرین ',
          'logs': 'لاگ',
          'Download Full Log': 'دانلود لاگ کامل',
          'Show': 'نمایش',
          'Filter': 'فیلتر',
          'Select Filter': 'انتخاب فیلتر',
          'Apply': 'اعمال',
          'Log Details': 'جزئیات لاگ',
          'Timestamp: ': 'زمان: ',
          'Message: ': 'پیام: ',
          'Close': 'بستن',
          'Nginx Logs': 'لاگ‌های Nginx',
          'Warnings:': 'هشدارها:',
          'IP: ': 'آی‌پی: ',
          'Request: ': 'درخواست: ',
          'Status: ': 'وضعیت: ',
          'Bytes: ': 'بایت‌ها: ',
          'Referrer: ': 'ارجاع‌دهنده: ',
          'User-Agent: ': 'عامل کاربر: ',
          'Filter Options': 'گزینه‌های فیلتر',
          'User Action Logs': 'لاگ‌های اقدامات کاربر',
          'Level: ': 'سطح: ',
          'Waf Logs': 'لاگ‌های WAF',
          'Clear All Logs': 'پاک کردن همه لاگ‌ها',
          'Method: ': 'روش: ',
          'Path: ': 'مسیر: ',
          'Alerts:': 'هشدارها:',
          'No alerts': 'بدون هشدار',
          'Rule ID: ': 'شناسه قانون: ',
          'Severity: ': 'شدت: ',
          'File: ': 'فایل: ',
          'Line: ': 'خط: ',
          'No logs available. Check data source or filters.': 'هیچ لاگی در دسترس نیست. منبع داده یا فیلترها را بررسی کنید.',
          'This will clear all logs. Proceed?': 'این کار همه لاگ‌ها را پاک می‌کند. ادامه می‌دهید؟',
          'No': 'خیر',
          'Yes': 'بله',
          '#': 'شماره',
          'IP Address': 'آدرس آی‌پی',
          'Logs': 'لاگ‌ها',
          'Results': 'نتایج',
          'Summary': 'خلاصه',
          'Log Statistics':'امار کلی',
          'Add Website': 'اضافه کردن Website',
          'WAF is OFF': 'WAF خاموش است',
          'WAF is ON!':'WAF روشن است',
          'Rule Manager': 'مدیریت قوانین',
          'Waf Manager': 'مدیریت WAF',
          'About': 'کاربران',
          'Users': 'مدیریت کاربران',
          'General Configuration': 'کانفینگ پنل',
          'Active Connections': 'یوزر های متصل شده',
          'Routes': 'مسیر ها',
          'Add virtual IP': 'اضافه کردن IP مجازی',
          'List Virtual IPs': 'لیست IP های مجازی',
          'Cinematic Mode': 'حالت سینمایی',
          'Nginx Log': 'گزارش های Nginx',
          'Waf Log': 'گزارش های WAF',
          'System': 'سیستم ها',
          'User Actions Log': 'گزارش های ورود و کاربران',
          'Interfaces': 'اینترفیس ها',
          'Viewers': 'بازدید کنندگان',
          'Time remaining:   ': "زمان باقی مانده:    ",
          'Beta version.If you exprience any problem or having a suggestion please tell us.': 'نسخه ازمایشی.با در اختیار گذاشتن خطا ها باگ ها و یا پیشنهاداتنون ما را در مسیر ساخت تجربه ایی بهتر یاری کنید! با تشکر',
          'فارسی': 'English',
          'ModSec Admin Panel': 'پنل ادمین ModSec',
          'Dashboard': 'داشبورد',
          'CPU Usage': 'مصرف CPU',
          'Cloud Usage': 'مصرف ابر',
          'Memory Usage': 'مصرف حافظه',
          'Traffic Usage': 'مصرف ترافیک',
          'Attacks per Application': 'حملات به ازای برنامه',
          'Welcome Admin!': 'خوش آمدید ادمین!',
          'Time remaining:': 'زمان باقی مانده:',
          'admin1': 'ادمین1',
          'Error': 'خطا',
          'Please fill the inputs correctly!': 'لطفا ورودی ها را به درستی پر کنید!',
          'Login Successful!': 'ورود موفقیت آمیز!',
          'Welcome dear test.': 'خوش آمدید تست عزیز.',
          'Invalid username or password': 'نام کاربری یا رمز عبور نامعتبر است',
          'Check your internet connection !': 'اتصال اینترنت خود را بررسی کنید!',
          'Logout': 'خروج',
          'Are you sure you want to logout?': 'آیا مطمئنید که می‌خواهید خارج شوید؟',
          'Cancel': 'لغو',
          'Confirm': 'تایید',
          'Profile': 'پروفایل',
          'Settings': 'تنظیمات',
          'Idle Alert': 'هشدار عدم فعالیت',
          'You have been idle for some min. Do you want to stay?': 'برای چند دقیقه بیکار بوده‌اید. آیا می‌خواهید بمانید؟',
          'YES': 'بله',
          'Statistics': 'آمار',
          'System Log': 'لاگ سیستم',
          'Dark Mode': 'حالت تاریک',
          'Language': 'زبان',
          'Login': 'ورود',
          'Welcome to WAF2Flutter!': 'خوش آمدید به WAF2Flutter!',
          'Username': 'نام کاربری',
          'Password': 'رمز عبور',
          'Demo Login method using pre defined username and pass': 'روش ورود آزمایشی با استفاده از نام کاربری و رمز عبور از پیش تعیین شده',
          'Status': 'وضعیت',
          'Visitors: ': 'بازدیدکنندگان: ',
          'Last refresh: ': 'آخرین بروزرسانی: ',
          'Suspected: ': 'مشکوک: ',
          'Critical: ': 'بحرانی: ',
          'Safe': 'ایمن',
          'Websites': 'وب سایت ها',
          'Quick Summary': 'خلاصه فعالیت ها',
          'Warnings': 'هشتار ها',
          'Critical': 'بحرانی',
          'Messages': 'پیغام ها',
          'All Requests': 'تمام درخواست ها',
          'Total Requests': 'همه ی درخواست ها',
          'Most Requests Day': 'بیشترین درخواست روزانه',
          'Todays Traffic': 'ترافیک امروز:',
          'Unique IPs': 'ایپی یکتا:',
          'Warnings: ': ':هشتار ها',
          'Total Requests: ': 'همه درخواست های ارسال شده:',
          'Waf Actions': 'اقدامات WAF',
          'Loading': 'در حال بارگذاری',
          'Checking status...': 'در حال بررسی وضعیت...',
          'Unable to get status': 'عدم توانایی در دریافت وضعیت',
          'Unsafe': 'ناامن',
          'Check Confg': 'بررسی پیکربندی',
          'Start Engine': 'شروع موتور',
          'Stop Engine': 'توقف موتور',
          'WAF started successfully!': 'WAF با موفقیت شروع شد!',
          'Failed to start WAF': 'راه‌اندازی WAF ناموفق بود',
          'WAF stopped successfully!': 'WAF با موفقیت متوقف شد!',
          'Failed to stop WAF': 'توقف WAF ناموفق بود',
          'Update Status': 'وضعیت به‌روزرسانی',
          'Refresh Status': 'تازه‌سازی وضعیت',
          'please refresh to check..': 'لطفاً برای بررسی تازه‌سازی کنید...',
          'Current: ': 'فعلی: ',
          'WAF Radar Overview': 'نمای کلی رادار WAF',
          'Critical Errors': 'خطاهای بحرانی',
          'No triggered rules found.': 'هیچ قانون فعال‌شده‌ای یافت نشد.',
          'The #': 'شماره ',
          'most triggered rule: ': 'قانون با بیشترین فعال‌سازی: ',
          'Configuration Files': 'فایل‌های پیکربندی',
          'ModSecurity': 'ModSecurity',
          'CRS Setup': 'تنظیمات CRS',
          'Nginx': 'Nginx',
          'Config File: ': 'فایل پیکربندی: ',
          'Content of ': 'محتوای ',
          'Enter your configuration here...': 'پیکربندی خود را اینجا وارد کنید...',
          'Restore': 'بازگرداندن',
          'Save': 'ذخیره',
          'Content cannot be empty': 'محتوا نمی‌تواند خالی باشد',
          'updated successfully': 'با موفقیت به‌روزرسانی شد',
          'Failed to update ': 'به‌روزرسانی ناموفق بود ',
          'restored successfully': 'با موفقیت بازگردانی شد',
          'Failed to restore ': 'بازگردانی ناموفق بود ',
          'Enter title of the rule:': 'عنوان قانون را وارد کنید:',
          'Type rule name...': 'نام قانون را تایپ کنید...',
          'Content of the rule': 'محتوای قانون',
          'Rule added successfully': 'قانون با موفقیت اضافه شد',
          'Please fill in both fields': 'لطفاً هر دو فیلد را پر کنید',
          'Change Waf Mode': 'تغییر حالت WAF',
          'Critical ! The dangerous requests cannot be blocked waf is off!': 'بحرانی! درخواست‌های خطرناک نمی‌توانند مسدود شوند، WAF خاموش است!',
          'Warning waf is only detect the Critical requests.': 'هشدار: WAF فقط درخواست‌های بحرانی را تشخیص می‌دهد.',
          'Waf is blooking Critical Requests!': 'WAF درخواست‌های بحرانی را مسدود می‌کند!',
          'Change': 'تغییر',
          'SecRuleEngine set to ': 'موتور قانون امنیتی تنظیم شد به ',
          'successfully': 'با موفقیت',
          'Failed to set SecRuleEngine': 'تنظیم موتور قانون امنیتی ناموفق بود',
          'Your IP Server: ': 'سرور IP شما: ',
          'Search among rules:': 'جستجو در میان قوانین:',
          'Create New Rule': 'ایجاد قانون جدید',
          'Download': 'دانلود',
          'Rules restored successfully': 'قوانین با موفقیت بازگردانی شدند',
          'Failed to restore rules': 'بازگردانی قوانین ناموفق بود',
          'Manage ModSecurity rules and configuration': 'مدیریت قوانین و پیکربندی ModSecurity',
          'Rule Name': 'نام قانون',
          'Edit Rule': 'ویرایش قانون',
          'Remove': 'حذف',
          'This shows the status of the rule (enabled/disabled)': 'این وضعیت قانون (فعال/غیرفعال) را نشان می‌دهد',
          'You can delete this rule via this key': 'می‌توانید این قانون را از طریق این کلید حذف کنید',
          'Rule status updated.': 'وضعیت قانون به‌روزرسانی شد.',
          'Failed to update rule status.': 'به‌روزرسانی وضعیت قانون ناموفق بود.',
          'Rule deleted successfully': 'قانون با موفقیت حذف شد',
          'Failed to delete rule': 'حذف قانون ناموفق بود',
          'Enter rule content...': 'محتوای قانون را وارد کنید...',
          'Disable Cinematic Mode': 'غیرفعال کردن حالت سینمایی',
          'Enable Cinematic Mode': 'فعال کردن حالت سینمایی',
          'Upload this website to the server': 'بارگذاری این وب‌سایت به سرور',
          'Deploy this website to the server': 'استقرار این وب‌سایت به سرور',
          'Delete this website from the pending list': 'حذف این وب‌سایت از لیست در انتظار',
          'Add New Application': 'افزودن برنامه جدید',
          'Application Name': 'نام برنامه',
          'Application Url': 'آدرس برنامه',
          'Applications Pending to Preview': 'برنامه‌های در انتظار پیش‌نمایش',
          'Name': 'نام',
          'Actions': 'اقدامات',
          'No pending applications.': 'هیچ برنامه در انتظاری وجود ندارد.',
          'Please fill in both fields.': 'لطفاً هر دو فیلد را پر کنید.',
          'Cannot upload. Current status: ': 'نمی‌توان بارگذاری کرد. وضعیت فعلی: ',
          'This website is already deployed.': 'این وب‌سایت قبلاً مستقر شده است.',
          'Cannot deploy. Current status: ': 'نمی‌توان مستقر کرد. وضعیت فعلی: ',
          'Canceled': 'لغو شد',
          'You have canceled': '.',
          'Introduce': 'معرفی',
          'Setup': 'نصب و راه‌اندازی',
          'Control Panel': 'پنل کنترل',
          'API Reference': 'مرجع API',
          'Developer Final Thoughts': 'نظرات نهایی توسعه‌دهنده',
          'Dark Mode': 'حالت تاریک',
          'فارسی': 'فارسی',
          'Welcome to WAF Manager': 'به مدیر WAF خوش آمدید',
          'The WAF Manager is a powerful tool for managing Web Application Firewalls (WAFs), monitoring website security, and configuring server settings. This section introduces its key features and how to get started.': 'مدیر WAF ابزاری قدرتمند برای مدیریت فایروال‌های برنامه‌های وب (WAF)، نظارت بر امنیت وب‌سایت و پیکربندی تنظیمات سرور است. این بخش ویژگی‌های کلیدی و نحوه شروع را معرفی می‌کند.',
          'Key Features': 'ویژگی‌های کلیدی',
          '- Website Management: Add, edit, deploy, and monitor websites.\n- WAF Configuration: Manage ModSecurity rules and exclusions.\n- Log Statistics: View audit and debug logs with summaries.\n- Responsive Interface: Works on mobile, tablet, and desktop.\n- Customization: Toggle dark mode, cinematic mode, and languages (English/Persian).': '- مدیریت وب‌سایت: افزودن، ویرایش، استقرار و نظارت بر وب‌سایت‌ها.\n- پیکربندی WAF: مدیریت قوانین ModSecurity و استثناها.\n- آمار لاگ‌ها: مشاهده لاگ‌های حسابرسی و دیباگ با خلاصه‌ها.\n- رابط پاسخگو: در موبایل، تبلت و دسکتاپ کار می‌کند.\n- سفارشی‌سازی: تغییر حالت تاریک، حالت سینمایی و زبان‌ها (انگلیسی/فارسی).',
          'How to Use': 'نحوه استفاده',
          '1. Navigate using the sidebar (visible on desktop or via the menu icon on mobile).\n2. Start by adding a website in the Setup section.\n3. Use the Control Panel to manage WAF settings and view logs.\n4. Refer to the API Reference for advanced integrations.\n5. Check Developer Final Thoughts for tips and best practices.': '1. با استفاده از نوار کناری (در دسکتاپ قابل مشاهده یا از طریق آیکون منو در موبایل) حرکت کنید.\n2. با افزودن یک وب‌سایت در بخش نصب و راه‌اندازی شروع کنید.\n3. از پنل کنترل برای مدیریت تنظیمات WAF و مشاهده لاگ‌ها استفاده کنید.\n4. برای ادغام‌های پیشرفته به مرجع API مراجعه کنید.\n5. برای نکات و بهترین روش‌ها، نظرات نهایی توسعه‌دهنده را بررسی کنید.',
          'Next Steps': 'گام‌های بعدی',
          'Go to the Setup section to add your first website or explore the Control Panel to manage existing ones.': 'به بخش نصب و راه‌اندازی بروید تا اولین وب‌سایت خود را اضافه کنید یا پنل کنترل را برای مدیریت وب‌سایت‌های موجود کاوش کنید.',
          'Setup Guide': 'راهنمای نصب و راه‌اندازی',
          'This section explains how to add and deploy websites in the WAF Manager application.': 'این بخش نحوه افزودن و استقرار وب‌سایت‌ها در برنامه مدیر WAF را توضیح می‌دهد.',
          'Adding a New Website': 'افزودن وب‌سایت جدید',
          '1. Navigate to the Add Website section via the sidebar.\n2. In the Add New Application panel:\n   - Enter an Application Name (e.g., \'MyWebsite\', no spaces).\n   - Enter the Application URL (e.g., \'www.mywebsite.com\').\n3. Click \'Save\' to add the website to the pending list.\n4. A confirmation message will appear if successful.': '1. از طریق نوار کناری به بخش افزودن وب‌سایت بروید.\n2. در پنل افزودن برنامه جدید:\n   - نام برنامه را وارد کنید (مثلاً \'MyWebsite\'، بدون فاصله).\n   - آدرس URL برنامه را وارد کنید (مثلاً \'www.mywebsite.com\').\n3. روی \'ذخیره\' کلیک کنید تا وب‌سایت به لیست در انتظار اضافه شود.\n4. در صورت موفقیت، پیام تأیید ظاهر می‌شود.',
          'Managing Pending Websites': 'مدیریت وب‌سایت‌های در انتظار',
          'Pending websites appear in the Applications Pending to Preview table. For each website, you can:\n- Upload: If the status is \'Waiting for zip\', click the upload icon to provide a zip file.\n- Deploy: If the status is \'Ready to deploy!\', click the cloud upload icon to deploy to the server.\n- Delete: Click the delete icon to remove the website from the list.\nNote: Ensure the status is correct before performing actions. Errors will display as snackbar messages.': 'وب‌سایت‌های در انتظار در جدول برنامه‌های در انتظار پیش‌نمایش ظاهر می‌شوند. برای هر وب‌سایت می‌توانید:\n- بارگذاری: اگر وضعیت \'در انتظار فایل زیپ\' است، روی آیکون بارگذاری کلیک کنید تا فایل زیپ را ارائه دهید.\n- استقرار: اگر وضعیت \'آماده برای استقرار!\' است، روی آیکون بارگذاری ابری کلیک کنید تا به سرور مستقر شود.\n- حذف: روی آیکون حذف کلیک کنید تا وب‌سایت از لیست حذف شود.\nتوجه: قبل از انجام اقدامات، از صحت وضعیت مطمئن شوید. خطاها به صورت پیام‌های اسنک‌بار نمایش داده می‌شوند.',
          'Tips': 'نکات',
          '- Verify the URL format before saving.\n- Upload valid zip files to avoid deployment errors.\n- Check the Control Panel to manage deployed websites.': '- قبل از ذخیره، فرمت URL را بررسی کنید.\n- فایل‌های زیپ معتبر را بارگذاری کنید تا از خطاهای استقرار جلوگیری شود.\n- پنل کنترل را برای مدیریت وب‌سایت‌های مستقر بررسی کنید.',
          'The Control Panel is the central hub for managing websites, configuring WAF settings, and monitoring logs.': 'پنل کنترل مرکز اصلی برای مدیریت وب‌سایت‌ها، پیکربندی تنظیمات WAF و نظارت بر لاگ‌ها است.',
          'Website Management': 'مدیریت وب‌سایت',
          '1. Access the Websites Dashboard via the Control Panel.\n2. Use the tabs:\n   - Websites Running: View active websites.\n   - Disabled Websites: View inactive websites.\n3. For each website:\n   - View Logs: Click the magnifying glass to see audit/debug logs.\n   - Edit: Click the edit icon to configure settings.\n   - Start/Stop: Use play/pause icons to toggle status.\n   - Delete: Click the delete icon and confirm.\n   - Mode: Select \'enabled\' or \'disabled\' from the dropdown.': '1. از طریق پنل کنترل به داشبورد وب‌سایت‌ها دسترسی پیدا کنید.\n2. از تب‌ها استفاده کنید:\n   - وب‌سایت‌های در حال اجرا: مشاهده وب‌سایت‌های فعال.\n   - وب‌سایت‌های غیرفعال: مشاهده وب‌سایت‌های غیرفعال.\n3. برای هر وب‌سایت:\n   - نمایش لاگ‌ها: روی آیکون ذره‌بین کلیک کنید تا لاگ‌های حسابرسی/دیباگ را ببینید.\n   - ویرایش: روی آیکون ویرایش کلیک کنید تا تنظیمات را پیکربندی کنید.\n   - شروع/توقف: از آیکون‌های پخش/توقف برای تغییر وضعیت استفاده کنید.\n   - حذف: روی آیکون حذف کلیک کنید و تأیید کنید.\n   - حالت: از منوی کشویی \'فعال\' یا \'غیرفعال\' را انتخاب کنید.',
          'WAF Configuration': 'پیکربندی WAF',
          '1. Select a website and go to the WAF Protection tab.\n2. Manage ModSecurity rules:\n   - Search: Filter rules by name.\n   - Create: Click \'Create New Rule\', enter title/content, and save.\n   - Edit: Click \'Edit Rule\' to modify content.\n   - Delete: Click the delete icon.\n   - Toggle: Enable/disable rules with the switch.\n3. Backup/Restore:\n   - Download: Save a backup of rules.\n   - Restore: Upload a backup file.\n4. Configure Exclusions:\n   - Local: Set exclusion paths, rule IDs, or attack names.\n   - Global: Set global rule exclusions.': '1. یک وب‌سایت را انتخاب کنید و به تب حفاظت WAF بروید.\n2. مدیریت قوانین ModSecurity:\n   - جستجو: قوانین را بر اساس نام فیلتر کنید.\n   - ایجاد: روی \'ایجاد قانون جدید\' کلیک کنید، عنوان/محتوا را وارد کرده و ذخیره کنید.\n   - ویرایش: روی \'ویرایش قانون\' کلیک کنید تا محتوا تغییر کند.\n   - حذف: روی آیکون حذف کلیک کنید.\n   - تغییر: با استفاده از سوئیچ، قوانین را فعال/غیرفعال کنید.\n3. پشتیبان‌گیری/بازیابی:\n   - دانلود: نسخه پشتیبان قوانین را ذخیره کنید.\n   - بازیابی: فایل پشتیبان را بارگذاری کنید.\n4. پیکربندی استثناها:\n   - محلی: مسیرهای استثناء، شناسه‌های قانون یا نام‌های حمله را تنظیم کنید.\n   - جهانی: استثناهای قانون جهانی را تنظیم کنید.',
          'Log Statistics': 'آمار لاگ‌ها',
          '1. Audit Logs:\n   - Summary: View attack summary charts and counts (Critical, Warning, Notice, Error, Total Requests).\n   - Audit Logs: Click a log to see details (ID, Timestamp, Level, Message).\n   - Reload: Refresh the log list.\n2. Debug Logs:\n   - Filter: Select entries (5-100), enter search terms, or choose a log level (e.g., Error).\n   - Refresh: Reload logs.\n   - Details: Click a log to view full information.': '.'
              'لاگ‌های حسابرسی:\n   - خلاصه: نمودارهای خلاصه حملات و تعداد (بحرانی، هشدار، اطلاع، خطا، کل درخواست‌ها) را مشاهده کنید.\n   - لاگ‌های حسابرسی: روی یک لاگ کلیک کنید تا جزئیات (شناسه، زمان، سطح، پیام) را ببینید.\n   - بارگذاری مجدد: لیست لاگ‌ها را تازه کنید.\n2. لاگ‌های دیباگ:\n   - فیلتر: تعداد ورودی‌ها (5-100)، اصطلاحات جستجو را وارد کنید یا سطح لاگ را انتخاب کنید (مثلاً خطا).\n   - تازه‌سازی: لاگ‌ها را مجدداً بارگذاری کنید.\n   - جزئیات: روی یک لاگ کلیک کنید تا اطلاعات کامل را مشاهده کنید.',
          'Interface Customization': 'سفارشی‌سازی رابط کاربری',
          '- Cinematic Mode: Toggle for a blurred background effect.\n- Dark Mode: Switch via the sidebar.\n- Language: Switch to Persian.\n- Responsive: Adapts to mobile, tablet, and desktop.': '- حالت سینمایی: برای اثر پس‌زمینه مات تغییر دهید.\n- حالت تاریک: از طریق نوار کناری تغییر دهید.\n- زبان: به فارسی تغییر دهید.\n- پاسخگو: با موبایل، تبلت و دسکتاپ سازگار است.',
          'This section provides guidance on using the WAF Manager’s backend APIs for advanced tasks.': 'این بخش راهنمایی‌هایی برای استفاده از APIهای بک‌اند مدیر WAF برای وظایف پیشرفته ارائه می‌دهد.',
          'Overview': 'بررسی اجمالی',
          'The WAF Manager interacts with a backend server to perform actions like fetching logs, updating configurations, and managing rules. APIs are used for:\n- Retrieving audit and debug logs.\n- Managing ModSecurity rules.\n- Deploying websites.\n- Updating Nginx and ModSecurity configurations.': 'مدیر WAF با یک سرور بک‌اند برای انجام اقداماتی مانند بازیابی لاگ‌ها، به‌روزرسانی پیکربندی‌ها و مدیریت قوانین تعامل می‌کند. APIها برای موارد زیر استفاده می‌شوند:\n- بازیابی لاگ‌های حسابرسی و دیباگ.\n- مدیریت قوانین ModSecurity.\n- استقرار وب‌سایت‌ها.\n- به‌روزرسانی پیکربندی‌های Nginx و ModSecurity.',
          'How to Use APIs': 'نحوه استفاده از APIها',
          '1. Obtain an API token from your administrator.\n2. Use a tool like Postman or cURL to send requests.\n3. Include the token in the Authorization header.\n4. Refer to the endpoint documentation (contact your administrator for details).\nNote: API endpoints are not publicly exposed in this guide. Request access for specific documentation.': '1. یک توکن API از مدیر خود دریافت کنید.\n2. از ابزاری مانند Postman یا cURL برای ارسال درخواست‌ها استفاده کنید.\n3. توکن را در هدر Authorization وارد کنید.\n4. به مستندات نقطه پایانی مراجعه کنید (برای جزئیات با مدیر خود تماس بگیرید).\nتوجه: نقاط پایانی API در این راهنما به صورت عمومی منتشر نمی‌شوند. برای مستندات خاص درخواست کنید.',
          'Example Actions': 'نمونه اقدامات',
          '- Fetch Logs: Retrieve audit logs for a website.\n- Update Rule: Modify a ModSecurity rule.\n- Deploy Website: Deploy a pending website to the server.\nContact support for endpoint URLs and parameters.': '- بازیابی لاگ‌ها: لاگ‌های حسابرسی برای یک وب‌سایت را بازیابی کنید.\n- به‌روزرسانی قانون: یک قانون ModSecurity را اصلاح کنید.\n- استقرار وب‌سایت: یک وب‌سایت در انتظار را به سرور مستقر کنید.\nبرای URL‌های نقطه پایانی و پارامترها با پشتیبانی تماس بگیرید.',
          'This section shares insights and best practices from the WAF Manager developers to help you use the application effectively.': 'این بخش بینش‌ها و بهترین روش‌ها را از توسعه‌دهندگان مدیر WAF به اشتراک می‌گذارد تا به شما در استفاده مؤثر از برنامه کمک کند.',
          'Best Practices': 'بهترین روش‌ها',
          '- Regularly Monitor Logs: Check audit and debug logs weekly to catch potential issues.\n- Backup Rules: Always download a backup before modifying WAF rules.\n- Test Deployments: Use the pending website feature to preview before deploying.\n- Update Configurations Carefully: Validate Nginx and ModSecurity changes to avoid errors.\n- Use Filters: Narrow down logs with search and level filters for faster analysis.': '- نظارت منظم بر لاگ‌ها: لاگ‌های حسابرسی و دیباگ را هفتگی بررسی کنید تا مشکلات احتمالی را شناسایی کنید.\n- پشتیبان‌گیری از قوانین: همیشه قبل از تغییر قوانین WAF یک نسخه پشتیبان دانلود کنید.\n- تست استقرارها: از ویژگی وب‌سایت در انتظار برای پیش‌نمایش قبل از استقرار استفاده کنید.\n- به‌روزرسانی پیکربندی‌ها با دقت: تغییرات Nginx و ModSecurity را برای جلوگیری از خطاها اعتبارسنجی کنید.\n- استفاده از فیلترها: با استفاده از فیلترهای جستجو و سطح، لاگ‌ها را برای تحلیل سریع‌تر محدود کنید.',
          'Tips for Efficiency': 'نکاتی برای کارایی',
          '- Enable Cinematic Mode for a modern interface (optional).\n- Switch to Persian for localized text if preferred.\n- Use tooltips (hover over icons) for quick action descriptions.\n- Contact support for API access to automate tasks.\n- Keep the application updated for new features and security fixes.': '- حالت سینمایی را برای رابط کاربری مدرن فعال کنید (اختیاری).\n- در صورت تمایل به فارسی برای متن بومی تغییر دهید.\n- از نکات ابزار (هاور روی آیکون‌ها) برای توضیحات سریع اقدامات استفاده کنید.\n- برای دسترسی به API برای خودکارسازی وظایف با پشتیبانی تماس بگیرید.\n- برنامه را برای ویژگی‌های جدید و رفع اشکالات امنیتی به‌روز نگه دارید.',
          'Support': 'پشتیبانی',
          'For issues, contact your system administrator or support team. Provide log details and error messages for faster resolution.': 'برای مشکلات، با مدیر سیستم یا تیم پشتیبانی تماس بگیرید. جزئیات لاگ و پیام‌های خطا را برای حل سریع‌تر ارائه دهید.',
          'You have canceled the action.': 'شما اقدام را لغو کرده‌اید.',
          'Websites Running': 'وب‌سایت‌های در حال اجرا',
          'Disable Websites': 'وب‌سایت‌های غیرفعال',
          'Listens to': 'گوش می‌دهد به',
          'Real web server': 'سرور وب واقعی',
          'Status Notes': 'یادداشت‌های وضعیت',
          'Mode': 'حالت',
          'Website Started': 'وب‌سایت شروع شد',
          'Confirm Deletion': 'تأیید حذف',
          'This action cannot be undone': 'این اقدام قابل بازگشت نیست',
          'WAF Protection': 'حفاظت WAF',
          'Configuration': 'پیکربندی',
          'Audit Logs for ': 'لاگ‌های حسابرسی برای ',
          'Audit Logs': 'لاگ‌های حسابرسی',
          'Attack Summary': 'خلاصه حملات',
          'Warning: ': 'هشدار: ',
          'Notice: ': 'اطلاع: ',
          'Error: ': 'خطا: ',
          'Reload': 'بارگذاری مجدد',
          'audit logs': 'لاگ‌های حسابرسی',
          'No audit logs available.': 'هیچ لاگ حسابرسی در دسترس نیست.',
          'Audit Log Details': 'جزئیات لاگ حسابرسی',
          'ID: ': 'شناسه: ',
          'entries': 'ورودی‌ها',
          'Search': 'جستجو',
          'Local rule exclusion': 'استثنای قانون محلی',
          'Exclusion Path:': 'مسیر استثنا: ',
          'Rule ID:': 'شناسه قانون: ',
          'Attack Name:': 'نام حمله: ',
          'Global Exclusion': 'استثنای جهانی',
          'Debug Logs': 'لاگ‌های دیباگ',

          'Debug Log Details': 'جزئیات لاگ دیباگ',
          'Refresh': 'تازه‌سازی',
          'Nginx Configuration': 'پیکربندی Nginx',
          'ModSecurity Configuration': 'پیکربندی ModSecurity',
        },
      };
}
